version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: autoestetia_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: autoestetia
      POSTGRES_PASSWORD: autoestetia123
      POSTGRES_DB: autoestetia_pro
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
